
services:
  java_app:
     container_name: java_app
     image: banking-java-app:1.0.0
     build: .
     ports:
      - "8081:8081"

     environment:
       -DATABASE_URL: jdbc:postgresql://postgresql:5432/banking
       -DATABASE_USERNAME: postgres
       -DATABASE_PASSWORD: password
     depends_on:
      - postgres

  postgres:
    container_name: postgres_container_bank
    image: postgres:latest
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      GDATA: /data/postgres
    ports:
      - "5432:5432"

    restart: unless-stopped